services:
  - type: web
    name: penapp
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FOOTBALL_DATA_KEY
        sync: false
